receivers:
  otlp:
    protocols:
      #endpoint: 0.0.0.0:4318
      grpc:
       endpoint: 0.0.0.0:4317


processors:



connectors:
  datadog/connector:


exporters:
  datadog/exporter:
    api:
      key: <ADD API KEY HERE>

service:
  pipelines:
    traces:
      receivers: [otlp]

      exporters: [datadog/connector, datadog/exporter]
    metrics:
      receivers: [datadog/connector, otlp] 
      exporters: [datadog/exporter]
    #logs:
    #  receivers: [otlp]
    #  processors: [memory_limiter, batch]
    #  exporters: [datadog]